/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.group4sos;

/**
 *
 * @author Kiel Lanzanas
 */
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
public class MenuPage extends javax.swing.JFrame {

    /**
     * Creates new form MenuPage
     */
    public MenuPage() {
        initComponents();
        addListeners();
        setLocationRelativeTo(null);
        // Change the color of the joptionpane
        UIManager.put("OptionPane.background", new Color(204, 126, 63));
        UIManager.put("OptionPane.messagebackground", new Color(204, 126, 63));
        UIManager.put("Panel.background", new Color(204, 126, 63));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl4 = new javax.swing.JLabel();
        MenuPanel = new javax.swing.JPanel();
        btnPlay = new javax.swing.JButton();
        btnMechanics = new javax.swing.JButton();
        lblS1 = new javax.swing.JLabel();
        lblO = new javax.swing.JLabel();
        lblS2 = new javax.swing.JLabel();
        lblmaryosep = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        titleLbl4.setFont(new java.awt.Font("Will", 1, 80)); // NOI18N
        titleLbl4.setForeground(new java.awt.Color(0, 102, 204));
        titleLbl4.setText("S");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MenuPanel.setBackground(new java.awt.Color(204, 126, 63));
        MenuPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        btnPlay.setBackground(new java.awt.Color(184, 126, 63));
        btnPlay.setFont(new java.awt.Font("Will", 1, 18)); // NOI18N
        btnPlay.setText("<html><font color='#660000'>Pl</font><font color='#0066ff'>ay</font></html>");
        btnPlay.setActionCommand("Play ");
        btnPlay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnMechanics.setBackground(new java.awt.Color(184, 126, 63));
        btnMechanics.setFont(new java.awt.Font("Will", 1, 18)); // NOI18N
        btnMechanics.setText("<html><font color='#660000'>How</font> to \n<font color='#0066ff'>Play</font></html>");
        btnMechanics.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblS1.setFont(new java.awt.Font("Will", 1, 60)); // NOI18N
        lblS1.setForeground(new java.awt.Color(0, 102, 204));
        lblS1.setText("S");

        lblO.setFont(new java.awt.Font("Will", 1, 60)); // NOI18N
        lblO.setForeground(new java.awt.Color(102, 0, 0));
        lblO.setText("O");

        lblS2.setFont(new java.awt.Font("Will", 1, 60)); // NOI18N
        lblS2.setForeground(new java.awt.Color(0, 102, 204));
        lblS2.setText("S");

        lblmaryosep.setBackground(new java.awt.Color(0, 0, 0));
        lblmaryosep.setFont(new java.awt.Font("Will", 1, 60)); // NOI18N
        lblmaryosep.setText("maryosep!");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("<html><font color='#660000'>Game</font><font color='#0066CC'> by</font><font color='#000000'><b>: CinnaBon-Chon</b></font></html>");

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblS1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblO)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblS2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblmaryosep))
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMechanics, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblS2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblO, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblS1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmaryosep, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMechanics, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> {
        MenuPage menuPage = new MenuPage();
        menuPage.setVisible(true);
    });
}

private void addListeners() {
    btnPlay.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            SOS sosFrame = new SOS();
            sosFrame.setVisible(true);
            dispose(); // Close the MenuPage frame if needed
        }
    });

    btnMechanics.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            StringBuilder message = new StringBuilder();
            message.append("<html><ul>");
            message.append("<li>The game is played by two players taking turns in <br> placing \"S\" or \"O\" on the cells of the game grid.</li>");
            message.append("<li>The player that successfully creates an \"SOS\" pattern <br> either horizontally, vertically, or diagonally earns a point and <br> the next turn.</li>");
            message.append("<li>The game ends when all cells of the game grid as filled by <br> either \"S\" or \"O\" by the players.</li>");
            message.append("<li>The player with the most points collected wins the game.</li>");
            message.append("</ul></html>");

            JOptionPane.showMessageDialog(MenuPage.this, message.toString(), "Game Mechanics", JOptionPane.INFORMATION_MESSAGE);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JButton btnMechanics;
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblO;
    private javax.swing.JLabel lblS1;
    private javax.swing.JLabel lblS2;
    private javax.swing.JLabel lblmaryosep;
    private javax.swing.JLabel titleLbl4;
    // End of variables declaration//GEN-END:variables
}
